# Generated by Django 5.2.5 on 2025-08-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Adminlar'},
        ),
        migrations.AlterModelOptions(
            name='kitob',
            options={'verbose_name': 'Kitob', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='muallif',
            options={'verbose_name': 'Muallif', 'verbose_name_plural': 'Mualliflar'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Qayd', 'verbose_name_plural': 'Qaydlar'},
        ),
        migrations.AlterModelOptions(
            name='talaba',
            options={'verbose_name': 'Talaba', 'verbose_name_plural': 'Talabalar'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='ish_vaqti',
            field=models.CharField(choices=[('08:00-12:00', '08:00-12:00'), ('12:00-18:00', '12:00-18:00')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='olingan_sana',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='qaytarish_sana',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
